---
- name: Unmount all NFS mounts, change IP address, and remount NFS mounts
  hosts: all
  become: yes
  vars:
    interface_name: eth0           # Network interface to change IP
    new_ip_address: 192.168.1.100/24  # New IP address
    gateway: 192.168.1.1              # Gateway address
  tasks:
    - name: Find all NFS mounts
      ansible.builtin.command: cat /proc/mounts | grep nfs
      register: nfs_mounts
      changed_when: false

    - name: Unmount all NFS mounts
      ansible.builtin.command: umount {{ item.split()[1] }}
      with_items: "{{ nfs_mounts.stdout_lines }}"
      when: nfs_mounts.stdout_lines is defined and nfs_mounts.stdout_lines | length > 0

    - name: Set static IP address using nmcli
      ansible.builtin.command: nmcli con mod {{ interface_name }} ipv4.addresses {{ new_ip_address }} ipv4.gateway {{ gateway }} ipv4.method manual
      notify: restart network

    - name: Bring up the network connection
      ansible.builtin.command: nmcli con up {{ interface_name }}
      notify: restart network

    - name: Remount NFS mounts
      ansible.builtin.command: mount -a
      when: nfs_mounts.stdout_lines is defined and nfs_mounts.stdout_lines | length > 0

  handlers:
    - name: Restart network
      ansible.builtin.command: nmcli networking off && nmcli networking on

