#!/usr/bin/expect

# Set the timeout
set timeout 10

# Access environment variables from the shell
set user      $env(VM_OS_ADMIN)
set password  $env(VM_OS_ADMIN_PASS)
set keyfile   $env(VM_KEY_FILE)
set host      $env(IP)
set ssh_args  $env(SSH_ARGS)

# Perform ssh-copy-id
spawn ssh-copy-id -o StrictHostKeyChecking=no${ssh_args} -i $keyfile.pub $user@$host
expect {
    "continue connecting (yes/no)?" { send "yes\r"; exp_continue }
    "password:" { send "$password\r" }
}

expect eof

