---
- name: Restart network
  hosts: localhost
  become: no
  vars:
    cur_ip_address: 192.168.122.102     # Current IP address
    connection_name: enp1s0
  tasks:
 
    - name: Restart network
      ansible.builtin.shell: "{{ item }}"
      loop:
        - "ssh {{ cur_ip_address }} 'sudo nmcli con up ${CONNECTION_NAME} 2>&1 &> ~/change-ip.log.1 &'"
        - "sleep 2"


