---
- name: Unmount all NFS mounts, change IP address
  hosts: s102
  become: yes
  vars:
    new_ip_address: 192.168.122.100/24  # New IP address
    gateway: 192.168.122.1              # Gateway address
  tasks:
 
    - name: Find all NFS mount points
      shell: "/usr/bin/mount | grep ' type nfs' | awk '{print $3}'"
      register: nfs_mounts
      changed_when: false

    - name: Show the NFS mount points
      debug:
        var: nfs_mounts.stdout_lines

    - name: Unmount all NFS filesystems
      shell: "umount {{ item }}"
      loop: "{{ nfs_mounts.stdout_lines }}"
      when: nfs_mounts.stdout_lines | length > 0
      ignore_errors: yes  # To continue even if a mount is busy or fails to unmount

    - name: Confirm all NFS filesystems unmounted
      shell: "mount | grep ' type nfs' || echo 'No NFS mounts found'"
      register: nfs_check
      changed_when: false

    - name: Show the status of NFS mounts after unmount
      debug:
        var: nfs_check.stdout

    - name: Get the value of an environment variable CONNECTION_NAME
      shell: "source /home/OSADMIN/script/env/env_server_info.sh && echo $CONNECTION_NAME"
      register: conn_name
      changed_when: false

    - name: Set Ansible variable from environment variable connection_name
      set_fact:
        connection_name: "{{ conn_name.stdout }}"

    - name: Set static IP address using nmcli
      ansible.builtin.shell: "{{ item }}"
      loop:
        - "nmcli con mod {{ connection_name }} ipv4.addresses {{ new_ip_address }} ipv4.gateway {{ gateway }} ipv4.method manual"


