---
- name: Manage NFS mount and network settings on RHEL
  hosts: your_target_host
  tasks:
    - name: Get connection name for specific IP address
      shell: |
        for conn in $(nmcli -t -f NAME connection show | grep -v '^lo$'); do
          ip=$(nmcli -t -f IP4.ADDRESS connection show "$conn" | cut -d/ -f1 | grep '192.168.122')
          if [ ! -z "$ip" ]; then
            echo "$conn"
            break
          fi
        done
      register: conn_name
      changed_when: false

    - name: Unmount NFS share
      command: umount /nfs
      ignore_errors: yes

    - name: Change IP address
      nmcli:
        conn_name: "{{ conn_name.stdout }}"
        ip4: "NEW_IP_ADDRESS/24"
        state: present
      notify:
        - Restart network

    - name: Remount NFS share
      mount:
        path: /nfs
        src: 192.168.122.1:/nfs
        fstype: nfs
        state: mounted

  handlers:
    - name: Restart network
      service:
        name: NetworkManager
        state: restarted
